server:
  port: 8090
spring:
  application:
    name: "trading-system"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trading-system-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.tradingsystem.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  config:
    import:
      - "application_dev.yml"
  profiles:
    active:
      "dev"


gpw:
  base-url: "<Place Production Gpw Address>"

account:
  username: "<Place Production Account Username>"
  accountId: 0

restclient:
  connectTimeoutMs: 5000
  readTimeoutMs: 10000
  maxConnTotal: 100
  maxConnPerRoute: 20
